
import type { CreepyCard } from '@/types';
import { generateCreepyImage } from '@/ai/flows/generate-creepy-image';

const phrases = [
  "The shadows in the corner began to dance.",
  "A faint whisper echoed from the empty room.",
  "The old doll's eyes seemed to follow you.",
  "It was not the wind rattling the windows.",
  "The reflection in the mirror wasn't smiling.",
  "Footsteps creaked on the stairs above, but no one was home.",
  "The phone rang, displaying 'Unknown Caller' from inside the house.",
  "A child's laughter came from the boarded-up attic.",
  "The scarecrow in the field moved at dusk.",
  "Written in dust on the table: 'I'm watching you.'",
  "The portrait's eyes shifted as you walked by.",
  "A cold spot lingered in the warmest part of the room.",
  "The old music box played a song you'd never heard.",
  "Something scratched from inside the walls.",
  "The path into the woods vanished behind you.",
];

const imageHints = [
  "eerie forest", "ghostly figure", "haunted mansion", "creepy doll", "dark silhouette",
  "monster shadow", "abstract horror", "spooky landscape", "ominous object", "spectral face",
  "abandoned room", "creepy corridor", "glowing eyes", "mysterious door", "twisted tree"
];

const TOTAL_INITIAL_CARDS = 80;
const UPFRONT_GENERATION_COUNT = 3; // Reduced from 5 to 3

export async function generateInitialCards(): Promise<CreepyCard[]> {
  const cards: CreepyCard[] = [];
  const goosebumpsStyleSuffix = ", in the vibrant, colorful, and spooky art style reminiscent of classic Goosebumps book covers.";
  
  for (let i = 0; i < TOTAL_INITIAL_CARDS; i++) {
    const phrase = phrases[i % phrases.length];
    const cardId = `initial-${i + 1}`;
    const placeholderImageUrl = `https://placehold.co/600x400.png`;
    const placeholderAiHint = imageHints[i % imageHints.length];

    if (i < UPFRONT_GENERATION_COUNT) {
      try {
        const imageResult = await generateCreepyImage({ prompt: phrase + goosebumpsStyleSuffix });
        cards.push({
          id: cardId,
          phrase: phrase,
          imageUrl: imageResult.imageDataUri,
          isAIGenerated: true,
          imageGenerated: true, // Successfully generated
        });
      } catch (error) {
        console.error(`Failed to generate initial image for card "${phrase}":`, error);
        cards.push({
          id: cardId,
          phrase: phrase,
          imageUrl: placeholderImageUrl,
          isAIGenerated: false,
          imageGenerated: true, // Attempted, failed, use placeholder, don't retry this one in batch
          aiHint: placeholderAiHint
        });
      }
    } else {
      // For cards beyond the initial upfront batch, set placeholder and mark for later generation
      cards.push({
        id: cardId,
        phrase: phrase,
        imageUrl: placeholderImageUrl,
        isAIGenerated: false, 
        imageGenerated: false, // Needs to be generated by batch process
        aiHint: placeholderAiHint
      });
    }
  }
  return cards;
}
